Logging to wandb run sevixdd/prior_debugging/1hz60r5h-rosy-water-1
Saving checkpoint locally
[34m[5mGrabbing data...
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/sevi/Documents/GitHub/FYP/train prior.py", line 770, in <module>
    main()
  File "/home/sevi/anaconda3/envs/AdvAI/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/sevi/anaconda3/envs/AdvAI/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/sevi/anaconda3/envs/AdvAI/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sevi/anaconda3/envs/AdvAI/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/sevi/Documents/GitHub/FYP/train prior.py", line 766, in main
    initialize_training(config_file, accelerator)
  File "/home/sevi/Documents/GitHub/FYP/train prior.py", line 700, in initialize_training
    img_reader = get_reader(
  File "/home/sevi/anaconda3/envs/AdvAI/lib/python3.8/site-packages/dalle2_pytorch/dataloaders/prior_loader.py", line 151, in get_reader
    image_reader = EmbeddingReader(
  File "/home/sevi/anaconda3/envs/AdvAI/lib/python3.8/site-packages/embedding_reader/embedding_reader.py", line 26, in __init__
    self.reader = ParquetNumpyReader(embeddings_folder, metadata_folder, meta_columns)
  File "/home/sevi/anaconda3/envs/AdvAI/lib/python3.8/site-packages/embedding_reader/parquet_numpy_reader.py", line 49, in __init__
    raise ValueError("No embeddings found in folder {embeddings_folder}")
ValueError: No embeddings found in folder {embeddings_folder}